name: 'lighthouse-badges-generator'
description: 'Greet someone and record the time'
inputs:
  commitMessage: # id of input
    description: 'Commit message'
    required: true
    default: '🚦 Add lighthouse bagdes!'
# outputs:
#   time: # id of output
#     description: 'The time we greeted you'
runs:
  using: 'node16'
  main: 'dist/index.js'
